// Run ONCE, on the developer's own machine, to create the signing keypair.
// Usage: node tools/generateKeypair.js
//
// Writes tools/private-key.pem (KEEP THIS SECRET — never ship it, commit it,
// or send it to anyone; it's what lets you mint new license keys) and embeds
// the matching public key into src/main/license-public-key.js (safe to ship
// inside the app — it can only verify signatures, not create them).

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const privateKeyPath = path.join(__dirname, 'private-key.pem');
if (fs.existsSync(privateKeyPath)) {
  console.error('tools/private-key.pem already exists. Refusing to overwrite it — doing so would');
  console.error('invalidate every license key you have already issued with it.');
  process.exit(1);
}

const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

fs.writeFileSync(privateKeyPath, privateKey, { mode: 0o600 });

const outFile = path.join(__dirname, '..', 'src', 'main', 'license-public-key.js');
fs.writeFileSync(
  outFile,
  `// Auto-generated by tools/generateKeypair.js. Safe to commit — this is the\n` +
  `// PUBLIC key only, it can verify license keys but cannot create new ones.\n` +
  `module.exports = ${JSON.stringify(publicKey)};\n`
);

console.log('Keypair generated.');
console.log('  Private key: tools/private-key.pem  (keep secret, do not commit or share)');
console.log('  Public key:  src/main/license-public-key.js  (embedded in the app, safe to ship)');
